version: '1.0'
services:
  esthetics-gpt:
    container_name: esthetics-gpt
    image: esthetics-gpt:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    resources:
      cpu: 1
      memory: 512Mi
